
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.3
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.3",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  email: 'email',
  passwordHash: 'passwordHash',
  firstName: 'firstName',
  lastName: 'lastName',
  avatar: 'avatar',
  status: 'status',
  lastLoginAt: 'lastLoginAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  preferences: 'preferences',
  emailVerifiedAt: 'emailVerifiedAt',
  mfaEnabled: 'mfaEnabled',
  mfaSecret: 'mfaSecret',
  mfaPending: 'mfaPending',
  mfaRecoveryCodes: 'mfaRecoveryCodes',
  failedLoginAttempts: 'failedLoginAttempts',
  lockedUntil: 'lockedUntil',
  passwordChangedAt: 'passwordChangedAt'
};

exports.Prisma.AccountContactScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  userId: 'userId',
  type: 'type',
  value: 'value',
  normalizedValue: 'normalizedValue',
  label: 'label',
  isPrimary: 'isPrimary',
  verifiedAt: 'verifiedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AccountContactVerificationScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  userId: 'userId',
  contactId: 'contactId',
  tokenHash: 'tokenHash',
  expiresAt: 'expiresAt',
  usedAt: 'usedAt',
  createdAt: 'createdAt'
};

exports.Prisma.PasskeyScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  userId: 'userId',
  credentialId: 'credentialId',
  publicKey: 'publicKey',
  counter: 'counter',
  transports: 'transports',
  name: 'name',
  deviceType: 'deviceType',
  backupEligible: 'backupEligible',
  backedUp: 'backedUp',
  aaguid: 'aaguid',
  lastUsedAt: 'lastUsedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserProfileScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  userId: 'userId',
  employeeId: 'employeeId',
  pronouns: 'pronouns',
  jobTitle: 'jobTitle',
  departmentId: 'departmentId',
  managerId: 'managerId',
  timezone: 'timezone',
  workingHoursStart: 'workingHoursStart',
  workingHoursEnd: 'workingHoursEnd',
  workingDays: 'workingDays',
  workingLocation: 'workingLocation',
  overview: 'overview',
  pronunciationAudioUrl: 'pronunciationAudioUrl',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserIdentityScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  userId: 'userId',
  provider: 'provider',
  subject: 'subject',
  email: 'email',
  createdAt: 'createdAt'
};

exports.Prisma.RoleScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  name: 'name',
  description: 'description',
  isSystem: 'isSystem',
  permissions: 'permissions',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserRoleScalarFieldEnum = {
  userId: 'userId',
  roleId: 'roleId',
  assignedAt: 'assignedAt'
};

exports.Prisma.ApiKeyScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  name: 'name',
  hashedKey: 'hashedKey',
  prefix: 'prefix',
  rateLimit: 'rateLimit',
  status: 'status',
  apiScopes: 'apiScopes',
  ipWhitelist: 'ipWhitelist',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AuthApiTokenScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  userId: 'userId',
  name: 'name',
  tokenHash: 'tokenHash',
  scopes: 'scopes',
  expiresAt: 'expiresAt',
  lastUsedAt: 'lastUsedAt',
  createdAt: 'createdAt'
};

exports.Prisma.UserSessionScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  userId: 'userId',
  token: 'token',
  device: 'device',
  browser: 'browser',
  ipAddress: 'ipAddress',
  location: 'location',
  isActive: 'isActive',
  startedAt: 'startedAt',
  lastActivityAt: 'lastActivityAt',
  expiresAt: 'expiresAt',
  refreshTokenHash: 'refreshTokenHash',
  refreshExpiresAt: 'refreshExpiresAt',
  rememberMe: 'rememberMe',
  deviceId: 'deviceId',
  platform: 'platform',
  appVersion: 'appVersion'
};

exports.Prisma.UserGroupScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  name: 'name',
  description: 'description',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserGroupMemberScalarFieldEnum = {
  groupId: 'groupId',
  userId: 'userId',
  joinedAt: 'joinedAt'
};

exports.Prisma.PasswordResetTokenScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  tenantId: 'tenantId',
  tokenHash: 'tokenHash',
  expiresAt: 'expiresAt',
  usedAt: 'usedAt',
  createdAt: 'createdAt'
};

exports.Prisma.EmailVerificationTokenScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  tenantId: 'tenantId',
  tokenHash: 'tokenHash',
  expiresAt: 'expiresAt',
  usedAt: 'usedAt',
  createdAt: 'createdAt'
};

exports.Prisma.EmailDeliveryScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  queueJobId: 'queueJobId',
  provider: 'provider',
  providerMessageId: 'providerMessageId',
  recipientHash: 'recipientHash',
  template: 'template',
  status: 'status',
  isCanary: 'isCanary',
  attemptedProviders: 'attemptedProviders',
  acceptedAt: 'acceptedAt',
  lastEventAt: 'lastEventAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EmailDeliveryEventScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  deliveryId: 'deliveryId',
  provider: 'provider',
  providerEventId: 'providerEventId',
  providerMessageId: 'providerMessageId',
  type: 'type',
  reason: 'reason',
  occurredAt: 'occurredAt',
  receivedAt: 'receivedAt'
};

exports.Prisma.EmailSuppressionScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  recipientHash: 'recipientHash',
  reason: 'reason',
  sourceProvider: 'sourceProvider',
  sourceEventId: 'sourceEventId',
  active: 'active',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EmailUsageDailyScalarFieldEnum = {
  tenantId: 'tenantId',
  usageDate: 'usageDate',
  reservedCount: 'reservedCount',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EmailSendReservationScalarFieldEnum = {
  tenantId: 'tenantId',
  queueJobId: 'queueJobId',
  usageDate: 'usageDate',
  createdAt: 'createdAt'
};

exports.Prisma.PushSubscriptionScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  userId: 'userId',
  endpoint: 'endpoint',
  p256dh: 'p256dh',
  auth: 'auth',
  label: 'label',
  createdAt: 'createdAt'
};

exports.Prisma.MfaPushChallengeScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  userId: 'userId',
  token: 'token',
  status: 'status',
  createdAt: 'createdAt',
  expiresAt: 'expiresAt'
};

exports.Prisma.OAuthClientScalarFieldEnum = {
  id: 'id',
  clientId: 'clientId',
  name: 'name',
  clientSecretHash: 'clientSecretHash',
  clientType: 'clientType',
  platformCode: 'platformCode',
  isFirstParty: 'isFirstParty',
  ownerTenantId: 'ownerTenantId',
  redirectUris: 'redirectUris',
  postLogoutRedirectUris: 'postLogoutRedirectUris',
  grantTypes: 'grantTypes',
  allowedScopes: 'allowedScopes',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AuthorizationCodeScalarFieldEnum = {
  id: 'id',
  codeHash: 'codeHash',
  clientId: 'clientId',
  userId: 'userId',
  tenantId: 'tenantId',
  sid: 'sid',
  redirectUri: 'redirectUri',
  scopes: 'scopes',
  nonce: 'nonce',
  codeChallenge: 'codeChallenge',
  codeChallengeMethod: 'codeChallengeMethod',
  expiresAt: 'expiresAt',
  consumedAt: 'consumedAt',
  createdAt: 'createdAt'
};

exports.Prisma.RefreshGrantScalarFieldEnum = {
  id: 'id',
  tokenHash: 'tokenHash',
  clientId: 'clientId',
  userId: 'userId',
  tenantId: 'tenantId',
  sid: 'sid',
  scopes: 'scopes',
  expiresAt: 'expiresAt',
  revokedAt: 'revokedAt',
  rotatedFromId: 'rotatedFromId',
  createdAt: 'createdAt'
};

exports.Prisma.ClientConsentScalarFieldEnum = {
  id: 'id',
  clientId: 'clientId',
  userId: 'userId',
  tenantId: 'tenantId',
  scopes: 'scopes',
  grantedAt: 'grantedAt',
  revokedAt: 'revokedAt'
};

exports.Prisma.OidcSigningKeyScalarFieldEnum = {
  id: 'id',
  alg: 'alg',
  publicJwk: 'publicJwk',
  privateKeyPemEnc: 'privateKeyPemEnc',
  status: 'status',
  createdAt: 'createdAt',
  retiredAt: 'retiredAt'
};

exports.Prisma.LoginAttemptCounterScalarFieldEnum = {
  id: 'id',
  ipHash: 'ipHash',
  attempts: 'attempts',
  lockedUntil: 'lockedUntil',
  firstSeenAt: 'firstSeenAt',
  lastSeenAt: 'lastSeenAt'
};

exports.Prisma.PlatformScalarFieldEnum = {
  code: 'code',
  name: 'name',
  port: 'port',
  baseUrl: 'baseUrl',
  icon: 'icon',
  audience: 'audience',
  requiresTenant: 'requiresTenant',
  lifecycle: 'lifecycle',
  surfaceType: 'surfaceType',
  isUserFacing: 'isUserFacing',
  discoverability: 'discoverability',
  category: 'category',
  sortWeight: 'sortWeight',
  minimumAssurance: 'minimumAssurance',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PlatformGrantScalarFieldEnum = {
  id: 'id',
  subjectType: 'subjectType',
  subjectId: 'subjectId',
  platformCode: 'platformCode',
  tenantId: 'tenantId',
  effect: 'effect',
  validFrom: 'validFrom',
  validUntil: 'validUntil',
  conditions: 'conditions',
  reason: 'reason',
  createdBy: 'createdBy',
  reviewAt: 'reviewAt',
  createdAt: 'createdAt'
};

exports.Prisma.AgentDefinitionScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  name: 'name',
  description: 'description',
  allowedPermissions: 'allowedPermissions',
  requiresConfirmationAbove: 'requiresConfirmationAbove',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AgentDelegationScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  agentId: 'agentId',
  delegatingUserId: 'delegatingUserId',
  effectivePermissions: 'effectivePermissions',
  sid: 'sid',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  User: 'User',
  AccountContact: 'AccountContact',
  AccountContactVerification: 'AccountContactVerification',
  Passkey: 'Passkey',
  UserProfile: 'UserProfile',
  UserIdentity: 'UserIdentity',
  Role: 'Role',
  UserRole: 'UserRole',
  ApiKey: 'ApiKey',
  AuthApiToken: 'AuthApiToken',
  UserSession: 'UserSession',
  UserGroup: 'UserGroup',
  UserGroupMember: 'UserGroupMember',
  PasswordResetToken: 'PasswordResetToken',
  EmailVerificationToken: 'EmailVerificationToken',
  EmailDelivery: 'EmailDelivery',
  EmailDeliveryEvent: 'EmailDeliveryEvent',
  EmailSuppression: 'EmailSuppression',
  EmailUsageDaily: 'EmailUsageDaily',
  EmailSendReservation: 'EmailSendReservation',
  PushSubscription: 'PushSubscription',
  MfaPushChallenge: 'MfaPushChallenge',
  OAuthClient: 'OAuthClient',
  AuthorizationCode: 'AuthorizationCode',
  RefreshGrant: 'RefreshGrant',
  ClientConsent: 'ClientConsent',
  OidcSigningKey: 'OidcSigningKey',
  LoginAttemptCounter: 'LoginAttemptCounter',
  Platform: 'Platform',
  PlatformGrant: 'PlatformGrant',
  AgentDefinition: 'AgentDefinition',
  AgentDelegation: 'AgentDelegation'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
