-- G09 — Data/object builder metadata: custom_object_definitions and
-- custom_object_field_definitions (custom-objects.prisma).
--
-- These two tables hold only the *definition* of a tenant-authored custom
-- object. The per-object data table itself (`co_<id>`) is generated by
-- CustomObjectSchemaService at request time, not by a migration — it cannot
-- be, since its columns are decided by what the tenant admin declares. Both
-- tables here get the same tenant_id + RLS treatment as every other tenant
-- table, hand-authored per the established pattern (see
-- 20260805130000_extension_installations) rather than via `prisma migrate
-- dev`, whose interactive diff against this schema currently proposes
-- dropping live IDP tables it does not know about — filed in
-- 90-DEFECT-LOG.md, out of scope for this migration.

CREATE TABLE "custom_object_definitions" (
  "id"                 TEXT NOT NULL,
  "tenant_id"          TEXT NOT NULL,
  "api_name"           TEXT NOT NULL,
  "label"              TEXT NOT NULL,
  "description"        TEXT,
  "status"             TEXT NOT NULL DEFAULT 'ACTIVE',
  "table_name"         TEXT NOT NULL,
  "created_by_user_id" TEXT,
  "created_at"         TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at"         TIMESTAMP(3) NOT NULL,
  CONSTRAINT "custom_object_definitions_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "custom_object_definitions_tenant_id_api_name_key"
  ON "custom_object_definitions" ("tenant_id", "api_name");
CREATE INDEX "custom_object_definitions_tenant_id_status_idx"
  ON "custom_object_definitions" ("tenant_id", "status");

CREATE TABLE "custom_object_field_definitions" (
  "id"         TEXT NOT NULL,
  "tenant_id"  TEXT NOT NULL,
  "object_id"  TEXT NOT NULL,
  "name"       TEXT NOT NULL,
  "label"      TEXT NOT NULL,
  "type"       TEXT NOT NULL,
  "required"   BOOLEAN NOT NULL DEFAULT false,
  "indexed"    BOOLEAN NOT NULL DEFAULT false,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "custom_object_field_definitions_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "custom_object_field_definitions_object_id_name_key"
  ON "custom_object_field_definitions" ("object_id", "name");
CREATE INDEX "custom_object_field_definitions_tenant_id_object_id_idx"
  ON "custom_object_field_definitions" ("tenant_id", "object_id");

ALTER TABLE "custom_object_field_definitions"
  ADD CONSTRAINT "custom_object_field_definitions_object_id_fkey"
  FOREIGN KEY ("object_id") REFERENCES "custom_object_definitions"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- ── RLS: ENABLE + FORCE, so the migrating/seeding owner is not exempt ────────
ALTER TABLE "custom_object_definitions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "custom_object_definitions" FORCE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation_custom_object_definitions"
  ON "custom_object_definitions"
  USING ("tenant_id" = current_tenant_id())
  WITH CHECK ("tenant_id" = current_tenant_id());

ALTER TABLE "custom_object_field_definitions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "custom_object_field_definitions" FORCE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation_custom_object_field_definitions"
  ON "custom_object_field_definitions"
  USING ("tenant_id" = current_tenant_id())
  WITH CHECK ("tenant_id" = current_tenant_id());
